# Form implementation generated from reading ui file 'detection_form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_detection_settings_window(object):
    def setupUi(self, detection_settings_window):
        detection_settings_window.setObjectName("detection_settings_window")
        detection_settings_window.resize(291, 171)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=detection_settings_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 271, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.global_settings_groupBox = QtWidgets.QGroupBox(parent=self.verticalLayoutWidget)
        self.global_settings_groupBox.setObjectName("global_settings_groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.global_settings_groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 261, 123))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.card_type_checkBox = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.card_type_checkBox.setObjectName("card_type_checkBox")
        self.verticalLayout_4.addWidget(self.card_type_checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.margin_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.margin_label.setObjectName("margin_label")
        self.horizontalLayout.addWidget(self.margin_label)
        spacerItem = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.margin_lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.margin_lineEdit.setObjectName("margin_lineEdit")
        self.horizontalLayout.addWidget(self.margin_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.min_noise_lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.min_noise_lineEdit.setObjectName("min_noise_lineEdit")
        self.horizontalLayout_2.addWidget(self.min_noise_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.detect_preview_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.detect_preview_button.setObjectName("detect_preview_button")
        self.horizontalLayout_3.addWidget(self.detect_preview_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.done_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_3.addWidget(self.done_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.global_settings_groupBox)

        self.retranslateUi(detection_settings_window)
        QtCore.QMetaObject.connectSlotsByName(detection_settings_window)

    def retranslateUi(self, detection_settings_window):
        _translate = QtCore.QCoreApplication.translate
        detection_settings_window.setWindowTitle(_translate("detection_settings_window", "Detection Settings"))
        self.global_settings_groupBox.setTitle(_translate("detection_settings_window", "Global Settings"))
        self.card_type_checkBox.setText(_translate("detection_settings_window", "Bright/Dark Card Toggle"))
        self.margin_label.setText(_translate("detection_settings_window", "Margin"))
        self.label_2.setText(_translate("detection_settings_window", "Minimum Size Noise"))
        self.detect_preview_button.setText(_translate("detection_settings_window", "Detection with debug mode"))
        self.done_button.setText(_translate("detection_settings_window", "Done"))
