# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_global_form(object):
    def setupUi(self, global_form):
        global_form.setObjectName("global_form")
        global_form.resize(815, 591)
        self.scrollArea = QtWidgets.QScrollArea(parent=global_form)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 541, 541))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 522, 1027))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.img_widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.img_widget.setMinimumSize(QtCore.QSize(500, 1000))
        self.img_widget.setObjectName("img_widget")
        self.gridLayout.addWidget(self.img_widget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_template_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.select_template_button.setObjectName("select_template_button")
        self.horizontalLayout_2.addWidget(self.select_template_button)
        self.template_path = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.template_path.setEnabled(False)
        self.template_path.setObjectName("template_path")
        self.horizontalLayout_2.addWidget(self.template_path)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(global_form)
        QtCore.QMetaObject.connectSlotsByName(global_form)

    def retranslateUi(self, global_form):
        _translate = QtCore.QCoreApplication.translate
        global_form.setWindowTitle(_translate("global_form", "Form"))
        self.select_template_button.setText(_translate("global_form", "Select Template"))
